# Generated by Django 5.0.4 on 2024-04-19 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
                'db_table': 'cities',
                'ordering': ['id', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContainerFormType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Container Form Type',
                'verbose_name_plural': 'Container Form Types',
                'db_table': 'container_form_types',
                'ordering': ['id', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContainerProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('phone', models.CharField(blank=True, max_length=255, null=True, verbose_name='Phone')),
                ('site', models.CharField(blank=True, max_length=255, null=True, verbose_name='Site')),
            ],
            options={
                'verbose_name': 'Container Provider',
                'verbose_name_plural': 'Container Providers',
                'db_table': 'container_providers',
                'ordering': ['id', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContainerType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Container Type',
                'verbose_name_plural': 'Container Types',
                'db_table': 'container_types',
                'ordering': ['id', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
                'db_table': 'countries',
                'ordering': ['id', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContainerAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('schedule_date_from', models.DateTimeField(verbose_name='Schedule Date From')),
                ('schedule_date_to', models.DateTimeField(verbose_name='Schedule Date To')),
                ('from_city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='container_announcements_from_city', to='container_announcements.city')),
                ('to_city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='container_announcements_to_city', to='container_announcements.city')),
                ('container_form_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='container_announcements', to='container_announcements.containerformtype')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='container_announcements', to='container_announcements.containerprovider')),
                ('container_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='container_announcements', to='container_announcements.containertype')),
            ],
            options={
                'verbose_name': 'Container Announcement',
                'verbose_name_plural': 'Container Announcements',
                'db_table': 'container_announcements',
                'ordering': ['id', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cities', to='container_announcements.country'),
        ),
    ]
