# Generated by Django 5.0.4 on 2024-04-22 06:46

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('container_announcements', '0004_containerprovider_description_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='containerprovider',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Phone'),
        ),
    ]
