# Generated by Django 5.0.4 on 2024-04-22 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("container_announcements", "0005_alter_containerprovider_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="containerannouncement",
            name="shipping_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="container_announcements",
                to="container_announcements.shippingtype",
            ),
            preserve_default=False,
        ),
    ]
