# Generated by Django 5.0.4 on 2024-06-03 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('container_announcements', '0006_containerannouncement_shipping_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='containerprovider',
            name='instagram',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='containerprovider',
            name='telegram',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Telegram'),
        ),
        migrations.AddField(
            model_name='containerprovider',
            name='watsapp',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Watsapp'),
        ),
    ]
