# Generated by Django 5.0.4 on 2024-06-04 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('container_announcements', '0007_containerprovider_instagram_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='containerannouncement',
            name='currency',
            field=models.CharField(choices=[('uzs', 'UZS'), ('usd', 'USD')], default='uzs', max_length=100),
        ),
        migrations.AddField(
            model_name='containerannouncement',
            name='is_by_agreement',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='containerannouncement',
            name='price',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
