# Generated by Django 5.0.4 on 2024-07-05 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('container_announcements', '0008_containerannouncement_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='containerannouncement',
            name='schedule_time_from',
            field=models.TimeField(default='18:00', verbose_name='Schedule Time From'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='containerannouncement',
            name='schedule_time_to',
            field=models.TimeField(default='18:00', verbose_name='Schedule Time To'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shippingtype',
            name='bg_color',
            field=models.CharField(default='18:00', max_length=255, verbose_name='Color'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='containerannouncement',
            name='schedule_date_from',
            field=models.DateField(verbose_name='Schedule Date From'),
        ),
        migrations.AlterField(
            model_name='containerannouncement',
            name='schedule_date_to',
            field=models.DateField(verbose_name='Schedule Date To'),
        ),
    ]
