# Generated by Django 5.0.4 on 2024-06-04 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('container_announcements', '0008_containerannouncement_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='containerannouncement',
            name='currency',
            field=models.CharField(default='uzs', max_length=100),
        ),
    ]
