# Generated by Django 5.0.4 on 2024-07-15 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('container_announcements', '0009_containerannouncement_schedule_time_from_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='containerannouncement',
            options={'ordering': ['schedule_date_from', 'schedule_time_from'], 'verbose_name': 'Container Announcement', 'verbose_name_plural': 'Container Announcements'},
        ),
        migrations.RemoveField(
            model_name='city',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='containerformtype',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='containerprovider',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='containerprovider',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='containertype',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='country',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='shippingtype',
            name='name_en',
        ),
    ]
