# Generated by Django 5.0.4 on 2024-06-04 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
        ('container_announcements', '0009_alter_containerannouncement_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='containerannouncement',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='container_announcements_from_city', to='base.currency'),
        ),
    ]
