# Generated by Django 5.0.4 on 2024-08-08 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('container_announcements', '0010_alter_containerannouncement_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='containerannouncement',
            name='status',
            field=models.IntegerField(choices=[(1, 'Active'), (0, 'Draft')], default=1),
        ),
    ]
