# Generated by Django 5.0.4 on 2024-07-15 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_aboutcompany_desc_en_aboutcompany_desc_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutcompany',
            name='desc_en',
        ),
        migrations.RemoveField(
            model_name='aboutcompany',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='currency',
            name='name_en',
        ),
    ]
