# Generated by Django 5.0.4 on 2024-04-22 09:53

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logistics_services", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="logisticsservice",
            name="description_en",
            field=models.TextField(null=True, verbose_name="Description"),
        ),
        migrations.AddField(
            model_name="logisticsservice",
            name="description_ru",
            field=models.TextField(null=True, verbose_name="Description"),
        ),
        migrations.AddField(
            model_name="logisticsservice",
            name="description_uz",
            field=models.TextField(null=True, verbose_name="Description"),
        ),
        migrations.AddField(
            model_name="logisticsservice",
            name="name_en",
            field=models.CharField(max_length=255, null=True, verbose_name="Name"),
        ),
        migrations.AddField(
            model_name="logisticsservice",
            name="name_ru",
            field=models.CharField(max_length=255, null=True, verbose_name="Name"),
        ),
        migrations.AddField(
            model_name="logisticsservice",
            name="name_uz",
            field=models.CharField(max_length=255, null=True, verbose_name="Name"),
        ),
        migrations.AddField(
            model_name="logisticsservice",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                default="+998995251591",
                max_length=128,
                region=None,
                verbose_name="Phone",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="logisticsservice",
            name="site",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Site"
            ),
        ),
        migrations.AddField(
            model_name="logisticsservicetype",
            name="name_en",
            field=models.CharField(max_length=255, null=True, verbose_name="Name"),
        ),
        migrations.AddField(
            model_name="logisticsservicetype",
            name="name_ru",
            field=models.CharField(max_length=255, null=True, verbose_name="Name"),
        ),
        migrations.AddField(
            model_name="logisticsservicetype",
            name="name_uz",
            field=models.CharField(max_length=255, null=True, verbose_name="Name"),
        ),
    ]
