# Generated by Django 5.0.4 on 2024-06-04 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics_services', '0002_logisticsservice_description_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='logisticsservice',
            name='instagram',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='logisticsservice',
            name='telegram',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Telegram'),
        ),
        migrations.AddField(
            model_name='logisticsservice',
            name='watsapp',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Watsapp'),
        ),
    ]
