# Generated by Django 5.0.4 on 2024-06-04 10:04

import apps.logistics_services.models.services
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics_services', '0003_logisticsservice_instagram_logisticsservice_telegram_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='logisticsservice',
            name='image',
            field=models.ImageField(default='logistics_services/default.png', upload_to=apps.logistics_services.models.services.logistics_image_upload_location, verbose_name='Image'),
        ),
    ]
